FROM python:3.10

WORKDIR usr/app/flower_classification

COPY requirements_streamlit.txt requirements.txt
COPY app app
COPY streamlit_app streamlit_app

RUN pip install --upgrade pip && pip3 install --default-timeout=100 -r requirements.txt

WORKDIR streamlit_app
CMD streamlit run home.py

EXPOSE 8501





